// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voxwrmutvmlzwrvtfkmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZveHdybXV0dm1sendydnRma21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjE5NzYsImV4cCI6MjA3Mjk5Nzk3Nn0.R5dte8OaowpibyreEnGeL_e4w8o0ftftZ_lXqpiuDfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});